services:
  cart-service-mysql:
    image: mysql:8.0
    container_name: cart-service-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ec
      MYSQL_CHARSET: utf8mb4
    restart: always
    networks:
      - server_net
  order-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
#      MYSQL_ADDR: "root:123456@tcp(cart-service-mysql:3306)/ec?charset=utf8mb4&parseTime=True&loc=Local"
      MYSQL_ADDR: "root:123456@tcp(user_manage_mysql:3306)/ec?charset=utf8mb4&parseTime=True&loc=Local"
#    depends_on:
#      - order-service-mysql
    restart: always
    networks:
      - server_net
networks:
  server_net:
    external: true


