server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:order_service@tcp(mysql:3306)/order_db?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
