services:
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
      REDIS_ADDR: "redis:6379"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - etcd-server
    networks:
      server_net:

networks:
  server_net:
    external: true
