// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ai_manage/internal/biz"
	"ai_manage/internal/conf"
	"ai_manage/internal/data"
	"ai_manage/internal/server"
	"ai_manage/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	aiRepo := data.NewAiRepo(dataData, logger)
	aiUsecase := biz.NewAiUsecase(aiRepo, logger)
	aiService := service.NewAiService(aiUsecase)
	grpcServer := server.NewGRPCServer(confServer, aiService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
