services:
  auth-manage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
      REDIS_ADDR: "redis:6379"
    restart:
      always
    networks:
      server_net:
networks:
  server_net:
    external: true


