services:
  auth-manage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
    depends_on:
      - auth_manage_mysql
    restart:
      always
    networks:
      server_net:
networks:
  server_net:
    external: true


