services:
  auth_manage_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ec
      MYSQL_CHARSET: utf8mb4
    networks:
      server_net:
  auth-manage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
    ports:
      - "9200:9200"
    depends_on:
      - auth_manage_mysql
    restart:
      always
    networks:
      server_net:
networks:
  server_net:
    external: true


