services:
#  order-service-mysql:
#    image: mysql:8.0
#    container_name: order-service-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: ec
#      MYSQL_CHARSET: utf8mb4
#    restart: always
#    networks:
#      - server_net
  payment-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
#      MYSQL_ADDR: "root:123456@tcp(order-service-mysql:3306)/ec?charset=utf8mb4&parseTime=True&loc=Local"
      MYSQL_ADDR: "root:123456@tcp(user_manage_mysql:3306)/ec?charset=utf8mb4&parseTime=True&loc=Local"
      APP_ID: "9021000145615772"
      PRIVATE_KEY: "MIIEogIBAAKCAQEAgBA159elsjUIJ/Mjy1VI23qjKTYq98VIdiG0GE+ByuK6yw46+wgrlUrWoeVTb1llSTfOdl+Zo3VALErCsguM5W8mg2EYeUbClwdTL7rFH0L4fqvsp2Hk2yovmMH5G5R0373+1LD2poOZRpqG6Vs7NhauZtsAMFkbCOxFKbjqo9K3zY2KRlcjkMhMMBOHUy5AohuLiSGeBYq1B596AkeCUBLn3WCk49XNqM4rsELw4uWgXJWShysA2GywnidKsiAbfuiSOUcq3FOr4HryqMp9OIxGY1/0D3ZaUVVosgbzaoknYKazqkHyTJBrtH+lvzgWVldG7KntHIRrbNoV7rnLwQIDAQABAoIBAFkt8LwAmiydbY6UbMq+GzxsDI84X3endKx/D/EV/OaSOU4KHNyPdfpC4XBgSFf0QupX6HjaXh1MG2I8tZRTIszrOECpLufVdNDDkxRb1cXNV0qu4uA09bABkp+oBJdGLJVas8jdawXOAsD9/xEmLPefl9ecjmccxgzSq99AHHXz1kiguBdO8ZT1o0hVyKHYcFyU1REu9YwgXS+qgsGIIsTD3fB0dMHv4cxI4qM9/4ujWogjx+xCpoj2JvVzmET21EWPt2KWGebj6tf9zGUe8oorNAHDDcu5zOJbSRq5avX9j7q1/DBE7KyvcJ4cj8Kyhky1Wa0w3OD86YGHTw4ykiECgYEA5Q9vMVduI0070Ufvm2kLNzgkjcc1GAyZpA6OkWK98r0+DB8s2aNLU6XDYPil8gUD/EBAAhczGKd8DAQgTw0C0FwO/A5voKsQ+RZjXtWkte061wK63vIFHsQdKgLqTz8HNZ0wF/6vTBl+DwAHm/GMtMLcViBQg1osIeWQ2BDax5UCgYEAjx/zjh784CgLeYQNWBOM5T0yBrAB6dAeAymZlYDh/w9mjUzEgjdN6IEO52n8w+/TicWfe+gpnNkxzT/TXgHxdHx0NXuTIvPCsbxBfQjPdquTgEo5UWOKBceInmnPl8bOMDpTx7amlGAJJO2QyZpR3IPggGUT8kfWbYEiODzW+H0CgYBuV1sG98j0dHYGQJLp2FYwyXjCW132McupPeHroxdBYWwMRtBCHulgaA+QHPdDeKsMzp6G40oX7EZTO4Gc0vWyDUaioQmg6gcJFoHT4zKu+JJJlOUUFJ3mzi4GWNUqS4BbkVbjmCo1jGovK6J+uoM/aEbfrj1aqQttYLq/eo8JaQKBgF7nENhsM8FuzC0HItIEJKjcqw9EJgCjv0LZkr1PeItn6thGzwaJJV/GM9u+q5xAqkPwho/iobUfT6aJa94p67ER1PyhtC6486Bm9AW0kdxeaK/oh5kwJ5UteamQ/9XkPVQ9WNBUjKBWDbouzJLhgOZ3i6WXYGKGv+hceBRSQzkBAoGAPyrYoTU/iyNdofYGt1d78UlzgcC3Sps82T8qiDFU6y7jA9WO3inqX/9Qj5C7xbGuDkaaZa5phZK31zrZCgrz4daVVn+xl0bPIb//wp+jBY/0SwcWwq2L+4yonVbvx++t6DoDz5Z2iO3+jgLlRJtGrr+dxvvytok7BH4U4nJtp4s="
      ALIPAY_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBqZ6rS16AKz+tdXdQ/kNh+dosW4KBE3Fnc3D3kcimVQrk4s8uwm/NoUVAzKwJd+9ROycTOCuuryprtZR0t1a4ObqC/MiyuLIdCm2oOKBbAPFGuHTn1VypxYMkQApwoV74a/D5AJ2003rThQj7X2PryRe4KIUMFsOhfJ1ywAofTe6OFGSCPTUlECIURnFZh98TfyaKMvUiP8q7aRW/De2wxLbd5Eq5DAjR6sBKeyeB+b61o6Oqg2t8DIymSX/qRWydtgY1hPqBsrOu1irSMpWDXhgTWuMEnRUR4PoaipEPkTIMPHhhKZDzSeUoqbeyRj3jJF5S39mlZQ+pn9uVfRswIDAQAB"
      IS_PRODUCTION: 0
#    depends_on:
#      - order-service-mysql
    restart: always
    networks:
      - server_net
networks:
  server_net:
    external: true


