services:
  content_manage_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ec
      MYSQL_CHARSET: utf8mb4
    networks:
      server_net:
  user-manage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
      MYSQL_ADDR: "root:123456@tcp(content_manage_mysql:3306)/ec?charset=utf8mb4&parseTime=True&loc=Local"
      JWT_SECRET: "123456"
      ELASTIC_ADDR: ""
      ELASTIC_USERNAME: ""
      ELASTIC_PASSWORD: ""
    ports:
      - "9100:9100"
    depends_on:
      - content_manage_mysql
    restart: always
    networks:
      server_net:
  elasticsearch:
    image: elasticsearch:8.11.4
    environment:
      ELASTIC_PASSWORD: elastic
      xpack.security.enabled: "false"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
networks:
  server_net:
    external: true

