services:
  content_manage_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: goods
      MYSQL_CHARSET: utf8mb4
    networks:
      server_net:
  user-manage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
      MYSQL_ADDR: "root:123456@tcp(content_manage_mysql:3306)/goods?charset=utf8mb4&parseTime=True&loc=Local"
      JWT_SECRET: "123456"
      ELASTIC_ADDR: "https://elastic-search:9200"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
    ports:
      - "9100:9100"
    depends_on:
      - content_manage_mysql
    restart: always
    networks:
      server_net:
  elastic-search:
    image: elasticsearch:8.11.4
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "elastic"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
networks:
  server_net:
    external: true

