services:
  content-manage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ETCD_ADDR: "etcd-server:2379"
      MYSQL_ADDR: "root:123456@tcp(user_manage_mysql:3306)/ec?charset=utf8mb4&parseTime=True&loc=Local"
      ELASTIC_ADDR: "http://elastic-search:9200"
      CANNAL_ADDR: "canal-server:11111"
#    depends_on:
#      - content_manage_mysql
    restart: always
    networks:
      server_net:
  elastic-search:
    image: elasticsearch:8.11.4
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "elastic"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      server_net:
  kibana:
    image: kibana:8.11.4
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elastic-search:9200"
    networks:
      server_net:


networks:
  server_net:
    external: true