# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0b\x61pi.operate\"\x9b\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0cphone_number\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x11\n\tuser_name\x18\x04 \x01(\t\x12\x11\n\tuser_type\x18\x05 \x01(\x05\x12\x0f\n\x07img_url\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x08 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"N\n\x0cGetUserReply\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.api.operate.UserInfo\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t2I\n\x04User\x12\x41\n\x07GetUser\x12\x1b.api.operate.GetUserRequest\x1a\x19.api.operate.GetUserReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFO']._serialized_start=28
  _globals['_USERINFO']._serialized_end=183
  _globals['_GETUSERREQUEST']._serialized_start=185
  _globals['_GETUSERREQUEST']._serialized_end=213
  _globals['_GETUSERREPLY']._serialized_start=215
  _globals['_GETUSERREPLY']._serialized_end=293
  _globals['_USER']._serialized_start=295
  _globals['_USER']._serialized_end=368
# @@protoc_insertion_point(module_scope)
