services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ETCD_ADDR: "etcd-server"
      SERVER_ADDR: "172.22.0.55:2379"
      ARK_API_KEY: "33820f8b-9106-4e5d-9f98-c39739ca304a"
      ARK_BASE_URL: "https://ark.cn-beijing.volces.com/api/v3"
      MODEL_NAME: "doubao-1-5-pro-32k-250115"
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"

    networks:
      server_net:
        ipv4_address: 172.22.0.55

networks:
  server_net:
    external: true