// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"payment_system/internal/biz"
	"payment_system/internal/conf"
	"payment_system/internal/data"
	"payment_system/internal/server"
	"payment_system/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(dataData, logger)
	orderClient, cleanup2, err := data.NewOrderClient(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	orderStatusRepo := data.NewOrderStatusRepo(orderClient, logger)
	alipayUsecase := biz.NewAlipayUsecase(paymentRepo, orderStatusRepo, logger)
	paymentService := service.NewPaymentService(alipayUsecase)
	grpcServer := server.NewGRPCServer(confServer, paymentService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
